apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
#    openshift.io/node-selector: node-role.kubernetes.io/infra=
  labels:
    openshift.io/cluster-monitoring: "true"
