apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: router
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,router]}
#  maxUnavailable: null
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/router: ""
  paused: false
